# Generated by Django 4.2.7 on 2024-01-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tescha', '0002_remove_estudiante_user_alter_curso_creditos'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='curso_images/'),
        ),
    ]
